### ISSUE TITLE
🤩 Create Movie Website - Youtube Video Deleted

### ISSUE THREAD

**Issue by bayuapriansah** [LazyDeveloperr/MissPerfect-URL-BOT#2]
> Youtube video in this link Deleted by Youtube
> [🤩 Create Movie Website](https://www.youtube.com/watch?v=h3Uvr15ZPnc)
> https://www.youtube.com/watch?v=h3Uvr15ZPnc
> Can you guys provide new link for us to see the content?

**Comment by LazyDeveloperr** [comment]
I have removed this video from yt ! No problem - i will make another video on this topic 🙂
